name: CI Build
on:
  push:
  release:
    types: [published]

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_MAXSIZE: 256M
  CCACHE_COMPRESS: true
  ESP_IDF_VERSION: v5.5.2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: mk5-release
            ud_gen: MK5
            ud_debug: 0
            target: esp32s3
          - environment: mk6-release
            ud_gen: MK6
            ud_debug: 0
            target: esp32s3
          - environment: mk7-release
            ud_gen: MK7
            ud_debug: 0
            target: esp32s3
          - environment: mk8-release
            ud_gen: MK8
            ud_debug: 0
            target: esp32s3

          # Debug variant
          - environment: mk6-debug
            ud_gen: MK6
            ud_debug: 1
            target: esp32s3

          # Future release with ESP32-C6
          - environment: mkX-release
            ud_gen: MKX
            ud_debug: 0
            target: esp32c6

    env:
      # Enable verbose logging in debug artifacts for farmhub tags
      FARMHUB_LOG_VERBOSE: env,scheduling

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-${{ matrix.environment }}

      - name: Create dummy config directory
        run: |
          mkdir -p config && \
          echo "{}" > config/device-config.json

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          esp_idf_docker_image: lptr/esp-idf-clang
          target: ${{ matrix.target }}
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py build \
              -DUD_GEN=${{ matrix.ud_gen }} \
              -DUD_DEBUG=${{ matrix.ud_debug }} \
              -DFSUPLOAD=1 \
              -DFARMHUB_LOG_VERBOSE=${{ env.FARMHUB_LOG_VERBOSE }} \
              && \
            esp-idf-sbom create -o build/ugly-duckling.spdx build/project_description.json && \
            pyspdxtools --novalidation --infile build/ugly-duckling.spdx --outfile build/ugly-duckling.spdx.json && \
            ccache -s

      - name: clang-tidy
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          esp_idf_docker_image: lptr/esp-idf-clang
          target: ${{ matrix.target }}
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            ./generate-clang-tidy-compile-db.py && \
            clang-tidy -p build/clang-tidy $(find main components -type f -name '*.cpp' -not -path '*/test/*' -not -path '*/build/*')

      - name: Collect artifacts
        run: |
          mkdir -p work/artifacts
          cp build/ugly-duckling.bin work/artifacts/ugly-duckling-${{ matrix.environment }}.bin
          cp build/ugly-duckling.elf work/artifacts/ugly-duckling-${{ matrix.environment }}.elf
          cp build/bootloader/bootloader.bin work/artifacts/bootloader-${{ matrix.environment }}.bin
          cp build/bootloader/bootloader.elf work/artifacts/bootloader-${{ matrix.environment }}.elf
          cp build/ota_data_initial.bin work/artifacts/ota_data_initial-${{ matrix.environment }}.bin
          cp build/partition_table/partition-table.bin work/artifacts/partition-table-${{ matrix.environment }}.bin
          cp partitions.csv work/artifacts/partitions-${{ matrix.environment }}.csv
          cp build/flasher_args.json work/artifacts/flasher_args-${{ matrix.environment }}.json
          cp build/ugly-duckling.spdx work/artifacts/ugly-duckling-${{ matrix.environment }}.spdx
          cp build/ugly-duckling.spdx.json work/artifacts/ugly-duckling-${{ matrix.environment }}.spdx.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ugly-duckling-${{ matrix.environment }}
          path: work/artifacts/
          if-no-files-found: error

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          cxx-compiler: clang++
          source-dir: test/unit-tests
          build-dir: test/unit-tests/build-native

      - name: Run tests
        working-directory: test/unit-tests/build-native
        run: |
          ./ugly-duckling-unit-tests

  embedded-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-embedded-test

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32s3
          path: test/embedded-tests
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py build && \
            ccache -s

      - name: Run a Wokwi CI server
        uses: wokwi/wokwi-ci-server-action@v1

      - name: esp-idf test
        if: false # Temporarily disabled
        run: |
            docker run \
            -v .:/project \
            -v ./artifacts/pytest-logs:/logs \
            -w /project/test/embedded-tests \
            -e HOME=/tmp \
            --add-host=host.docker.internal:host-gateway \
            -e WOKWI_CLI_SERVER=ws://host.docker.internal:9177 \
            -e WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }} \
            lptr/pytest-embedded:latest \
            pytest \
              --embedded-services idf,wokwi \
              --root-logdir /logs \
              ./pytest_embedded-tests.py \
              --wokwi-timeout=120000

      - name: Upload pytest-embedded logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-embedded-logs
          path: |
            artifacts/pytest-logs/**
          if-no-files-found: warn

  e2e-test:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: ""

    steps:
      - uses: actions/checkout@v5

      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          ports: '1883:1883'
          config: ${{ github.workspace }}/.github/mosquitto/mosquitto.conf

      - name: Get Host IP
        run: |
          HOSTNAME=$(hostname -I | awk '{print $1}')
          echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-e2e-test

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32s3
          path: test/e2e-tests
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py -DUD_GEN=MK6 -DUD_DEBUG=1 -DFSUPLOAD=1 -DWOKWI=1 -DWOKWI_MQTT_HOST=${{ env.HOSTNAME }} build && \
            ccache -s

      - name: Run a Wokwi CI server
        uses: wokwi/wokwi-ci-server-action@v1

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        if: false # Temporarily disabled
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: test/e2e-tests
          timeout: 30000
          expect_text: 'Device ready'
          serial_log_file: 'log-hello-world.txt'

      # - name: esp-idf test
      #   run: |
      #     docker run -v .:/project -w /project/test/e2e-tests -e HOME=/tmp -e WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }} lptr/pytest-embedded:latest pytest --embedded-services idf,wokwi ./pytest_e2e-tests.py

  r2-publish:
    name: Publish OTA to Cloudflare R2
    needs:
      - build
    runs-on: ubuntu-latest
    concurrency:
      group: publish-ota-r2
      cancel-in-progress: false

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download workflow artifacts
        uses: actions/download-artifact@v5
        with:
          path: work/artifacts

      - name: Install dependencies
        working-directory: .github/publish-ota-r2
        run: npm ci

      - name: Run publisher
        working-directory: .github/publish-ota-r2
        run: |
          npx tsx publish-ota-r2.ts \
            --artifacts ../../work/artifacts \
            --repo-root ../.. \
            --base-url "${{ vars.R2_PUBLIC_URL }}" \
            --branch "${{ github.ref_name }}" \
            --commit-sha "${{ github.sha }}" \
            --keep-snapshot "0.32.11-11-g8552f75:Used in testing crash reports"
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}

  release:
    needs:
      - build
      - unit-test
      - embedded-test
      - e2e-test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: work/artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: work/artifacts/ugly-duckling-*/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
